#pragma once

#include <QStringList>

// The fonts heap ships inside the binary (qrc :/fonts, generated by
// tools/gen_bundled_fonts.py): Golos Text 400/500/600 for the interface and
// JetBrains Mono 400/500 for code, ids and times. Before they were bundled the
// UI asked for fonts most machines do not have and drew in Segoe UI / Consolas
// on Windows, something else on Linux and macOS.
//
// They are registered as "heap Golos Text" / "heap JetBrains Mono", never the
// upstream names: on Windows with JetBrains Mono installed, a bundled face
// under the same name got mixed with the installed one (glyph ids from one
// file, outlines from the other) and every time and count read as gibberish.
namespace heap::platform {

inline constexpr const char* kUiFontFamily = "heap Golos Text";
inline constexpr const char* kMonoFontFamily = "heap JetBrains Mono";

// Adds every bundled face to the application font database. Call once, after
// the QGuiApplication exists and before any QML loads. A face that cannot be
// added is logged as a warning; returns how many failed (0 = all in).
int registerBundledFonts();

// Makes Golos Text the application font (family only; the size stays the
// platform's). Text with no family of its own, the Controls' defaults and a
// font.family the machine does not have all end up in it, not in the system
// UI font. No-op when the family did not register.
void useBundledUiFontByDefault();

// What the font database cannot give back after registration: a missing
// family ("Golos Text") or a weight that resolves to another one
// ("Golos Text 600"). Empty when everything is there. --smoke reports these.
QStringList missingBundledFonts();

}  // namespace heap::platform
